"""Generate the browser resolver from the reviewed identity registry."""
import json
from pathlib import Path

try:
    from .team_identity import registry
except ImportError:
    from team_identity import registry

ROOT = Path(__file__).resolve().parent.parent


def render() -> str:
    rows, _ = registry()
    data = [{'name': r['canonical_name'], 'aliases': r['aliases'],
             'provider_ids': r['provider_ids']} for r in rows]
    return '''// Generated by src/export_team_identities.py; edit data/reference/team_identities.json.
(function (root) {
  const identities = ''' + json.dumps(data, ensure_ascii=False, separators=(',', ':')) + ''';
  const normalize = name => String(name || '').normalize('NFKD').toLowerCase()
    .replace(/[\\u0300-\\u036f]/g, '').replace(/[’']/g, '').replace(/\\s+/g, ' ').trim();
  function createResolver(teams, provider = 'cfbd_scoreboard') {
    const byName = new Map(teams.map(team => [team.name, team]));
    const index = new Map(), providerIndex = new Map(), expectedIds = new Map();
    function add(name, team) {
      if (!team) return;
      const key = normalize(name);
      if (index.has(key) && index.get(key) !== team) index.set(key, null);
      else if (!index.has(key)) index.set(key, team);
    }
    teams.forEach(team => add(team.name, team));
    identities.forEach(identity => {
      const team = byName.get(identity.name);
      identity.aliases.forEach(alias => add(alias, team));
      const id = identity.provider_ids[provider];
      if (id != null) {
        providerIndex.set(String(id), identity.name);
        expectedIds.set(identity.name, String(id));
      }
    });
    return side => {
      const team = index.get(normalize(side?.name));
      if (!team) return null;
      // IDs validate an exact name match; they never override a conflicting name
      // or cross from the provider namespace into internal database IDs.
      if (side.id != null) {
        const id = String(side.id), owner = providerIndex.get(id), expected = expectedIds.get(team.name);
        if (owner && owner !== team.name || expected && expected !== id) return null;
      }
      return team;
    };
  }
  const api = {createResolver};
  if (typeof module === 'object' && module.exports) module.exports = api;
  else root.CfbLiveTeams = api;
})(typeof globalThis !== 'undefined' ? globalThis : this);
'''


def export() -> None:
    (ROOT / 'ui/live_teams.js').write_text(render(), encoding='utf-8')


if __name__ == '__main__':
    export()
