"""
User-provided, per-team chip background colors -- takes priority over
build_dated_logo_assets.py's algorithmic extract_secondary_color() for
any team listed here. Scoped to teams only (not conferences); the user
supplied this specifically as university colors.

A few entries in the user's original list used a different name than
our canonical team_name (e.g. "Massachusetts / UMass", "Louisiana-
Monroe") or were marked with a trailing "*" for a team not in our FBS
roster at all (FCS/lower-division programs like Brown, Colgate,
Chattanooga) -- those "*" entries are simply omitted here since they'd
never be looked up against our team list anyway.
"""

TEAM_CHIP_COLOR_OVERRIDES = {
    "Air Force": "#E2E8F0",
    "Akron": "#E2E8F0",
    "Alabama": "#0F172A",
    "Appalachian State": "#1F2937",
    "Arizona": "#E2E8F0",
    "Arizona State": "#F8FAFC",
    "Arkansas": "#E2E8F0",
    "Arkansas State": "#E2E8F0",
    "Army": "#F8FAFC",
    "Auburn": "#F8FAFC",
    "Ball State": "#E2E8F0",
    "Baylor": "#E2E8F0",
    "Boise State": "#0F172A",
    "Boston College": "#F8FAFC",
    "Bowling Green": "#F1F5F9",
    "Buffalo": "#1F2937",
    "BYU": "#E2E8F0",
    "California": "#F8FAFC",
    "Central Michigan": "#0F172A",
    "Charlotte": "#111827",
    "Cincinnati": "#F8FAFC",
    "Clemson": "#0F172A",
    "Coastal Carolina": "#F8FAFC",
    "Colorado": "#F8FAFC",
    "Colorado State": "#0F172A",
    "Delaware": "#0F172A",
    "Duke": "#F8FAFC",
    "East Carolina": "#E2E8F0",
    "Eastern Michigan": "#E2E8F0",
    "FIU": "#FFE4E6",
    "Florida": "#0F172A",
    "FAU": "#E2E8F0",  # user's list: "Florida Atlantic"
    "Florida State": "#E2E8F0",
    "Fresno State": "#0F172A",
    "Georgia": "#E2E8F0",
    "Georgia Southern": "#FFE4E6",
    "Georgia State": "#E2E8F0",
    "Georgia Tech": "#0F172A",
    "Hawai'i": "#E2E8F0",
    "Houston": "#E2E8F0",
    "Illinois": "#0F172A",
    "Indiana": "#E2E8F0",
    "Iowa": "#F8FAFC",
    "Iowa State": "#F8FAFC",
    "Jacksonville State": "#E2E8F0",
    "James Madison": "#0F172A",
    "Kansas": "#0F172A",
    "Kansas State": "#E2E8F0",
    "Kennesaw State": "#F8FAFC",
    "Kent State": "#E2E8F0",
    "Kentucky": "#E2E8F0",
    "Liberty": "#E2E8F0",
    "Louisiana": "#0F172A",
    "ULM": "#F8FAFC",  # user's list: "Louisiana-Monroe"
    "Louisiana Tech": "#0F172A",
    "Louisville": "#E2E8F0",
    "LSU": "#E2E8F0",
    "Marshall": "#E0F2FE",
    "Maryland": "#E2E8F0",
    "Massachusetts": "#E2E8F0",  # user's list: "Massachusetts / UMass"
    "Memphis": "#E2E8F0",
    "Miami (FL)": "#0F172A",
    "Miami (OH)": "#E2E8F0",
    "Michigan": "#0F172A",
    "Michigan State": "#F8FAFC",
    "Middle Tennessee": "#E2E8F0",
    "Minnesota": "#0F172A",
    "Mississippi State": "#DBEAFE",
    "Missouri": "#E2E8F0",
    "Missouri State": "#E2E8F0",
    "Navy": "#0F172A",
    "NC State": "#E2E8F0",
    "Nebraska": "#111827",
    "Nevada": "#E2E8F0",
    "New Mexico": "#E2E8F0",
    "New Mexico State": "#111827",
    "North Carolina": "#0F172A",
    "North Dakota State": "#0F172A",
    "North Texas": "#E2E8F0",
    "Northern Illinois": "#E2E8F0",
    "Northwestern": "#E2E8F0",
    "Notre Dame": "#F8FAFC",
    "Ohio": "#E0F2FE",
    "Ohio State": "#FFE4E6",
    "Oklahoma": "#0F172A",
    "Oklahoma State": "#1F2937",
    "Old Dominion": "#FFF7ED",
    "Ole Miss": "#E2E8F0",
    "Oregon": "#0F172A",
    "Oregon State": "#E2E8F0",
    "Penn State": "#E2E8F0",
    "Pittsburgh": "#F8FAFC",
    "Purdue": "#F8FAFC",
    "Rice": "#E0F2FE",
    "Rutgers": "#E2E8F0",
    "Sacramento State": "#0F172A",
    "Sam Houston": "#0F172A",
    "San Diego State": "#E2E8F0",
    "San Jose State": "#0F172A",
    "South Alabama": "#0F172A",
    "South Carolina": "#E2E8F0",
    "South Florida": "#F8FAFC",
    "SMU": "#0F172A",
    "Southern Miss": "#1F2937",
    "Stanford": "#E2E8F0",
    "Syracuse": "#0F172A",
    "TCU": "#E2E8F0",
    "Temple": "#0F172A",
    "Tennessee": "#0F172A",
    "Texas": "#E2E8F0",
    "Texas A&M": "#E2E8F0",
    "Texas State": "#E2E8F0",
    "Texas Tech": "#E2E8F0",
    "Toledo": "#0F172A",
    "Troy": "#E2E8F0",
    "Tulane": "#E2E8F0",
    "Tulsa": "#E2E8F0",
    "UAB": "#0F172A",
    "UCF": "#F8FAFC",
    "UCLA": "#0F172A",
    "UConn": "#E2E8F0",
    "UNLV": "#E2E8F0",
    "USC": "#F8FAFC",
    "Utah": "#E2E8F0",
    "Utah State": "#E2E8F0",
    "UTEP": "#0F172A",
    "UTSA": "#E2E8F0",
    "Vanderbilt": "#F8FAFC",
    "Virginia": "#0F172A",
    "Virginia Tech": "#0F172A",
    "Wake Forest": "#F8FAFC",
    "Washington": "#0F172A",
    "Washington State": "#E2E8F0",
    "West Virginia": "#0F172A",
    "Western Kentucky": "#E2E8F0",
    "Western Michigan": "#0F172A",
    "Wisconsin": "#0F172A",
    "Wyoming": "#F8FAFC",
}
